[package]
name = "noisy-clippy"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies]
anyhow = "1.0"
flate2 = "1.0"
parking_lot = "0.11"
rayon = "1.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }
semver = "1.0"
serde = { version = "1.0", features = ["derive"] }
syn = { version = "1.0", default-features = false, features = ["full", "parsing", "visit"] }
tar = "0.4"
